### ISSUE TITLE
Does kube-batch support GPU?

### ISSUE THREAD

**Issue by chenyangxueHDU** [kubernetes-sigs/kube-batch#403]
i create a job like this.
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: qj-1
spec:
  backoffLimit: 6
  completions: 6
  parallelism: 6
  template:
    metadata:
      annotations:
        scheduling.k8s.io/group-name: qj-1
    spec:
      containers:
      - image: centos
        imagePullPolicy: IfNotPresent
        name: centos
        command:
        - bin/bash
        - -c
        - while true;do echo hello docker;sleep 1;done
        resources:
          limits:
            nvidia.com/gpu: 1
      restartPolicy: Never
      schedulerName: kube-batch
      nodeSelector:
        accelerator: p4
---
apiVersion: scheduling.incubator.k8s.io/v1alpha1
kind: PodGroup
metadata:
  name: qj-1
spec:
  numMember: 6
```
i have only 2 gpus, so i hope `kube-batch` will not start any pods for the Job.
but i found 2 pods running
```
NAME         READY     STATUS    RESTARTS   AGE
qj-1-4hj7j   1/1       Running   0          74s
qj-1-9xb44   0/1       Pending   0          74s
qj-1-ddktk   0/1       Pending   0          74s
qj-1-pk2jb   1/1       Running   0          74s
qj-1-t6nqz   0/1       Pending   0          74s
qj-1-z4nr8   0/1       Pending   0          74s

```
